### ISSUE TITLE
Remove "editing" functions if source is "trainset"

### ISSUE THREAD

**Issue by kaigoh** [ClintCWC/TimetablesFrontEnd#38]
I.e. disable / hide "Extract CIF", "Save Edits" etc.

**Comment by ClintCWC** [comment]
should i detect if at least 1 service is source trainset or should there be a flag somewhere (not sure where) that i can you to detect if the entire dataset of services comes from trainset?

**Comment by ClintCWC** [comment]
i have written some code to detect what the main source is for the service data.
however i am loading Dayset: Brighton to Ashford International SX out and i see no source flag in the service meta for the services, im guessing its because you have recently added this flag, i would normally re-extract cif but i cant do that with the trainset source service, can you refresh?

**Comment by ClintCWC** [comment]
disabled extract cif and save options for source = trainset
